#!/bin/sh
#Script that demos, command line argument
#
#USAGE ./command_line_arg Welcome India
#
echo "Total number of command line args"
echo "\"$0\" is script name"
echo "\"$1\" is first argument"
echo "\"$2\" is second argument"
echo "All of them are :- \"$*\" or \"$@\" "
